#' @title U-shaped Cedergreen-Ritz-Streibig model
#'
#' @description
#' \code{ucedergreen} provides a very general way of specifying the Cedergreen-Ritz-Streibig
#' modified log-logistic model for describing u-shaped hormesis, under various constraints on the parameters.
#'
#' @param fixed A numeric vector of length 5 specifying any parameters to be held fixed
#'   during the estimation. The order is \code{c(b, c, d, e, f)}. Use \code{NA} for
#'   parameters that should be estimated. The default is to estimate all parameters.
#' @param names A character vector of length 5 providing names for the parameters.
#'   The default is \code{c("b", "c", "d", "e", "f")}.
#' @param method A character string specifying the method for the self-starter function
#'   to use for finding initial parameter values. Options are \code{"loglinear"},
#'   \code{"anke"}, \code{"method3"}, and \code{"normolle"}. This is only used if \code{ssfct} is \code{NULL}.
#' @param ssfct A custom self-starter function. If \code{NULL} (the default), a
#'   self-starter is automatically generated by calling \code{\link{cedergreen.ssf}}
#'   with the specified \code{method}, \code{fixed}, and \code{alpha} arguments.
#' @param alpha A mandatory numeric value specifying the fixed shape parameter \eqn{\alpha}.
#'   The function will stop if this is not provided.
#' @param fctName An optional character string to name the function object.
#' @param fctText An optional character string providing a descriptive text for the model.
#'
#' @details
#' The u-shaped model is given by the expression
#' \deqn{f(x) = c + d - \frac{d-c+f \exp(-1/x^{\alpha})}{1+\exp(b(\log(x)-\log(e)))}}
#'
#' @return A list of class \code{"UCRS"}, containing the model function (\code{fct}),
#'   the self-starter function (\code{ssfct}), parameter names (\code{names}), and other
#'   components required for use with modeling functions like \code{\link[drc]{drm}}.
#'
#' @references
#' Cedergreen, N. and Ritz, C. and Streibig, J. C. (2005)
#' Improved empirical models describing hormesis,
#' \emph{Environmental Toxicology and Chemistry} \bold{24}, 3166--3172.
#'
#' @author Christian Ritz, Hannes Reinwald
#'
#' @seealso \code{\link{cedergreen}}, \code{\link{UCRS.4a}}, \code{\link{UCRS.5a}}, \code{\link{drm}}
#'
#' @keywords models nonlinear
"ucedergreen" <- function(
    fixed  = c(NA, NA, NA, NA, NA),
    names  = c("b", "c", "d", "e", "f"),
    method = c("loglinear", "anke", "method3", "normolle"),
    ssfct  = NULL,
    alpha,
    fctName,
    fctText
){
    ## Checking arguments and setting up fixed parameter logic
    numParm <- 5
    if (!is.character(names) || !(length(names) == numParm)) {stop("Not correct 'names' argument")}
    if (!(length(fixed) == numParm)) {stop("Not correct 'fixed' argument")}
    if (missing(alpha)) {stop("'alpha' argument must be specified")}

    # Determine if fixed parameters are being used. This will be passed to ssfct.
    useFixed <- !all(is.na(fixed))

    # Match the method argument
    method   <- match.arg(method)
    notFixed <- is.na(fixed)
    parmVec  <- rep(0, numParm)
    parmVec[!notFixed] <- fixed[!notFixed]

    ## Defining the non-linear function
    fct <- function(dose, parm)
    {
        parmMat <- matrix(parmVec, nrow(parm), numParm, byrow = TRUE)
        parmMat[, notFixed] <- parm

        numTerm <- parmMat[, 3] - parmMat[, 2] + parmMat[, 5]*exp(-1/dose^alpha)
        denTerm <- 1 + exp(parmMat[, 1]*(log(dose) - log(parmMat[, 4])))
        # U-shaped model: f(x) = c + d - numTerm/denTerm
        parmMat[, 2] + parmMat[, 3] - numTerm/denTerm
    }

    ## --- Correctly defining the self-starter ---
    # If a custom self-starter is not provided, use our robust cedergreen.ssf
    if (is.null(ssfct)) {
        # Delegate to the external self-starter, passing method, fixed, alpha, and useFixed.
        ssfct_inner <- cedergreen.ssf(method = method, fixed = fixed, alpha = alpha, useFixed = useFixed)
        ssfct <- function(dframe) {
            initval <- ssfct_inner(dframe)
            # For U-shaped model, negate the b parameter if it's not fixed
            if (is.na(fixed[1])) {
                initval[1] <- -initval[1]
            }
            return(initval)
        }
    }

    ## Defining names for the parameters to be estimated
    names <- names[notFixed]

    ## Specifying the derivatives
    deriv1 <- function(dose, parm)
    {
        parmMat <- matrix(parmVec, nrow(parm), numParm, byrow=TRUE)
        parmMat[, notFixed] <- parm

        t0 <- exp(-1/(dose^alpha))
        t1 <- parmMat[, 3] - parmMat[, 2] + parmMat[, 5]*t0
        t2 <- exp(parmMat[, 1]*(log(dose) - log(parmMat[, 4])))
        t3 <- 1 + t2
        t4 <- (1 + t2)^(-2)

        cbind( t1*xlogx(dose/parmMat[, 4], parmMat[, 1])*t4,
               1 + 1/t3,
               1 - 1/t3,
               -t1*t2*(parmMat[, 1]/parmMat[, 4])*t4,
               -t0/t3 )[, notFixed]
    }

    deriv2 <- NULL

    ## Defining the ED function: wrapper closure that delegates to cedergreen_edfct
    ## The framework calls edfct(parm, respl, reference, type, ...) so we bind
    ## parmVec, notFixed, and alpha from the enclosing scope.
    edfct <- function(parm, respl, reference, type, lower = 1e-4, upper = 10000, ...)
    {
        cedergreen_edfct(parm, parmVec, notFixed, alpha, 100 - respl, reference, type, lower, upper)
    }

    ## Finding the maximal hormesis: wrapper closure that delegates to cedergreen_maxfct
    ## The framework calls maxfct(parm, lower, upper) where parm is the non-fixed
    ## parameter vector. We reconstruct the full named-list and bind alpha.
    maxfct <- function(parm, lower = 1e-3, upper = 1000, .optimize_fn = stats::optimize)
    {
        parmVec[notFixed] <- parm
        all_params <- list(b = parmVec[1], c = parmVec[2], d = parmVec[3],
                           e = parmVec[4], f = parmVec[5])
        retVal <- cedergreen_maxfct(all_params, alpha, lower, upper, .optimize_fn)
        # For U-shaped: invert the response
        retVal[2] <- (parmVec[2] + parmVec[3]) - retVal[2]
        return(retVal)
    }

    # Return results
    returnList <- list(
        fct    = fct,
        ssfct  = ssfct,
        names  = names,
        deriv1 = deriv1,
        deriv2 = NULL,
        edfct  = edfct,
        maxfct = maxfct,
        name   = ifelse(missing(fctName), as.character(match.call()[[1]]), fctName),
        text   = ifelse(missing(fctText), "U-shaped Cedergreen-Ritz-Streibig", fctText),
        noParm = sum(is.na(fixed))
    )

    class(returnList) <- "UCRS"
    invisible(returnList)
}


#' @title U-shaped CRS model with lower limit 0 (alpha=1)
#'
#' @description
#' Four-parameter u-shaped CRS hormesis model with lower limit fixed at 0 and alpha=1.
#'
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#'
#' @return A list (see \code{\link{ucedergreen}}).
#'
#' @seealso \code{\link{ucedergreen}}, \code{\link{UCRS.5a}}, \code{\link{CRS.4a}}
#'
#' @keywords models nonlinear
"UCRS.4a" <-
function(names = c("b", "d", "e", "f"), ...)
{
    ## Checking arguments
    if (!is.character(names) || !(length(names) == 4)) {stop("Not correct 'names' argument")}

    return(ucedergreen(names = c(names[1], "c", names[2:4]), fixed = c(NA, 0, NA, NA, NA), alpha = 1, ...))
}

#' @title Alias for UCRS.4a
#' @description \code{uml3a} is an alias for \code{\link{UCRS.4a}}.
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#' @seealso \code{\link{UCRS.4a}}
#' @keywords models nonlinear
uml3a <- UCRS.4a

#' @title U-shaped CRS model with lower limit 0 (alpha=0.5)
#'
#' @description
#' Four-parameter u-shaped CRS hormesis model with lower limit fixed at 0 and alpha=0.5.
#'
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#'
#' @return A list (see \code{\link{ucedergreen}}).
#'
#' @seealso \code{\link{ucedergreen}}, \code{\link{UCRS.4a}}, \code{\link{CRS.4b}}
#'
#' @keywords models nonlinear
"UCRS.4b" <-
function(names = c("b", "d", "e", "f"), ...)
{
    ## Checking arguments
    if (!is.character(names) || !(length(names) == 4)) {stop("Not correct 'names' argument")}

    return(ucedergreen(names = c(names[1], "c", names[2:4]), fixed = c(NA, 0, NA, NA, NA), alpha = 0.5, ...))
}

#' @title Alias for UCRS.4b
#' @description \code{uml3b} is an alias for \code{\link{UCRS.4b}}.
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#' @seealso \code{\link{UCRS.4b}}
#' @keywords models nonlinear
uml3b <- UCRS.4b

#' @title U-shaped CRS model with lower limit 0 (alpha=0.25)
#'
#' @description
#' Four-parameter u-shaped CRS hormesis model with lower limit fixed at 0 and alpha=0.25.
#'
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#'
#' @return A list (see \code{\link{ucedergreen}}).
#'
#' @seealso \code{\link{ucedergreen}}, \code{\link{UCRS.4a}}, \code{\link{CRS.4c}}
#'
#' @keywords models nonlinear
"UCRS.4c" <-
function(names = c("b", "d", "e", "f"), ...)
{
    ## Checking arguments
    if (!is.character(names) || !(length(names) == 4)) {stop("Not correct 'names' argument")}

    return(ucedergreen(names = c(names[1], "c", names[2:4]), fixed = c(NA, 0, NA, NA, NA), alpha = 0.25, ...))
}

#' @title Alias for UCRS.4c
#' @description \code{uml3c} is an alias for \code{\link{UCRS.4c}}.
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#' @seealso \code{\link{UCRS.4c}}
#' @keywords models nonlinear
uml3c <- UCRS.4c

#' @title U-shaped CRS five-parameter model (alpha=1)
#'
#' @description
#' Five-parameter u-shaped CRS hormesis model with alpha=1.
#'
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#'
#' @return A list (see \code{\link{ucedergreen}}).
#'
#' @seealso \code{\link{ucedergreen}}, \code{\link{UCRS.4a}}, \code{\link{CRS.5a}}
#'
#' @keywords models nonlinear
"UCRS.5a" <-
function(names = c("b", "c", "d", "e", "f"), ...)
{
    ## Checking arguments
    if (!is.character(names) || !(length(names) == 5)) {stop("Not correct 'names' argument")}

    return(ucedergreen(names = names, fixed = c(NA, NA, NA, NA, NA), alpha = 1, ...))
}

#' @title Alias for UCRS.5a
#' @description \code{uml4a} is an alias for \code{\link{UCRS.5a}}.
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#' @seealso \code{\link{UCRS.5a}}
#' @keywords models nonlinear
uml4a <- UCRS.5a

#' @title U-shaped CRS five-parameter model (alpha=0.5)
#'
#' @description
#' Five-parameter u-shaped CRS hormesis model with alpha=0.5.
#'
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#'
#' @return A list (see \code{\link{ucedergreen}}).
#'
#' @seealso \code{\link{ucedergreen}}, \code{\link{UCRS.5a}}, \code{\link{CRS.5b}}
#'
#' @keywords models nonlinear
"UCRS.5b" <-
function(names = c("b", "c", "d", "e", "f"), ...)
{
    ## Checking arguments
    if (!is.character(names) || !(length(names) == 5)) {stop("Not correct 'names' argument")}

    return(ucedergreen(names = names, fixed = c(NA, NA, NA, NA, NA), alpha = 0.5, ...))
}

#' @title Alias for UCRS.5b
#' @description \code{uml4b} is an alias for \code{\link{UCRS.5b}}.
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#' @seealso \code{\link{UCRS.5b}}
#' @keywords models nonlinear
uml4b <- UCRS.5b

#' @title U-shaped CRS five-parameter model (alpha=0.25)
#'
#' @description
#' Five-parameter u-shaped CRS hormesis model with alpha=0.25.
#'
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#'
#' @return A list (see \code{\link{ucedergreen}}).
#'
#' @seealso \code{\link{ucedergreen}}, \code{\link{UCRS.5a}}, \code{\link{CRS.5c}}
#'
#' @keywords models nonlinear
"UCRS.5c" <-
function(names = c("b", "c", "d", "e", "f"), ...)
{
    ## Checking arguments
    if (!is.character(names) || !(length(names) == 5)) {stop("Not correct 'names' argument")}

    return(ucedergreen(names = names, fixed = c(NA, NA, NA, NA, NA), alpha = 0.25, ...))
}

#' @title Alias for UCRS.5c
#' @description \code{uml4c} is an alias for \code{\link{UCRS.5c}}.
#' @param names a vector of character strings giving the names of the parameters.
#' @param ... additional arguments passed to \code{\link{ucedergreen}}.
#' @seealso \code{\link{UCRS.5c}}
#' @keywords models nonlinear
uml4c <- UCRS.5c
